# Site settings
title: ""
description: ""
url: "https://johnwinston.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages compatibility
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md